[package]
name = "pong"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
laminar = "0.5.0"
bevy = { version = "0.7.0", features = ["dynamic"] }
tui = "0.18"
crossterm = "0.23"